### ISSUE TITLE
Missing entries while application was down ?

### ISSUE THREAD

**Issue by GingerHarry** [bravecollective/brave-bucks#5]
https://zkillboard.com/kill/93995549/
https://zkillboard.com/kill/93995422/
https://zkillboard.com/kill/93995223/
https://zkillboard.com/kill/93995144/

I dont know if there are more entries missing, just thought to bring it out because maybe others will be missing some as well.... 

BTW i like the Tool ! THX for service

**Comment by tkhamez** [comment]
Killmails aren't lost because of a short downtime.
