### ISSUE TITLE
Make compatible with latest LTS Java version

### ISSUE THREAD

**Issue by tkhamez** [bravecollective/brave-bucks#6]
Java 8 is supported longer than 11, so it should at least run with 17, otherwise it makes no sense.

**Comment by tkhamez** [comment]
It no longer needs to run with Java 8.

**Comment by tkhamez** [comment]
https://github.com/bravecollective/brave-bucks/pull/7

**Comment by tkhamez** [comment]
Java 8 is supported longer than 11, so it should at least run with 17, otherwise it makes no sense.

**Comment by tkhamez** [comment]
Perhaps it is better to rewrite it completely.

**Comment by Bombe** [comment]
> Perhaps it is better to rewrite it completely.

…said every software developer ever. 🤣

**Comment by tkhamez** [comment]
The app is being rewritten.

**Comment by qsheltier** [comment]
URL of new repository?
